version: "3.8"

x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"

  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  AIRFLOW_CONN_POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  # SQL Server con ODBC
  AIRFLOW_CONN_SQLSERVER: mssql+pyodbc://${MSSQL_USER}:${MSSQL_PASSWORD}@${MSSQL_HOST}:${MSSQL_PORT}/${MSSQL_DB}?driver=ODBC+Driver+17+for+SQL+Server

  OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}

  PYTHONPATH: /opt/airflow

x-airflow-common-volumes: &airflow-common-volumes
  - ./dags:/opt/airflow/dags
  - ./src:/opt/airflow/src
  - ./logs:/opt/airflow/logs
  - ./plugins:/opt/airflow/plugins
  - ./data:/opt/airflow/data

services:

  postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - airflow_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: airflow-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - airflow_net

  airflow-init:
    build: .
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *airflow-common-env
      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      AIRFLOW_ADMIN_EMAIL: ${AIRFLOW_ADMIN_EMAIL}
    volumes: *airflow-common-volumes
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create
      --username ${AIRFLOW_ADMIN_USER}
      --firstname Admin
      --lastname User
      --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL}
      --password ${AIRFLOW_ADMIN_PASSWORD}
      "
    networks:
      - airflow_net

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      <<: *airflow-common-env
    volumes: *airflow-common-volumes
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - airflow_net

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      <<: *airflow-common-env
    volumes: *airflow-common-volumes
    command: scheduler
    networks:
      - airflow_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  airflow_net: