FROM apache/airflow:2.9.1

USER root

# -------------------------------
# Dependencias del sistema
# -------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    freetds-dev \
    libpq-dev \
    unixodbc \
    unixodbc-dev \
    curl \
    gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------
# Driver ODBC para SQL Server
# -------------------------------
RUN mkdir -p /etc/apt/keyrings \
    && curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg \
    && echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/11/prod bullseye main" > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------
# Volver a usuario airflow
# -------------------------------
USER airflow

# -------------------------------
# Instalar dependencias Python
# -------------------------------
COPY requirements.txt .

ARG AIRFLOW_VERSION=2.9.1
ARG PYTHON_VERSION=3.10
ARG CONSTRAINT_URL=https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt

RUN pip install --no-cache-dir -r requirements.txt --constraint "${CONSTRAINT_URL}"